first_name: Ahmed
middle_name:
last_name: Abubaker
email: ahmed.abubaker1@ucdconnect.ie  
# description: Personal website of Ahmed Abubaker — monocular depth estimation researcher.
url: https://wdabdu.github.io
baseurl: ""        # ← MUST be empty for a user page (common mistake: don't put /repo-name)
keywords: monocular depth estimation, computer vision

# Social — fill what you have, leave the rest blank
github_username: wdabdu
scholar_userid:        https://scholar.google.com/citations?user=JpHcLYkAAAAJ&hl=en&authuser=2
orcid_id:              https://orcid.org/0009-0005-6942-3698
linkedin_username: https://www.linkedin.com/in/ahmed-abubaker-5b9066165/
